name: Go

on:
  push:
    branches:
    - master
    - feature/*
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: setup golang caches
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.49.0

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

    - name: go report card
      uses: creekorful/goreportcard-action@v1.0

    - name: codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        flags: unittests
        name: codecov-umbrella # optional